#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
##	sudo sh /home/pi/programs/command/PIpoweroff.sh
### BEGIN INIT INFO
# Provides:          PIpoweroff.sh
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update_hass.sh
### END INIT INFO

mkdir -p /home/pi/log/install
LOG_FILE="/home/pi/log/PIpoweroff.log"

#systemctl stop home-assistant@homeassistant.service          | tee -a 	"$LOG_FILE"

#start command#

systemctl stop home-assistant@homeassistant.service          | tee -a 	"$LOG_FILE"
rm /home/homeassistant/.homeassistant/home-assistant.log     | tee -a 	"$LOG_FILE"
rm /home/homeassistant/.homeassistant/home-assistant_v2.db   | tee -a 	"$LOG_FILE"

sleep 2 

/sbin/shutdown -h now


exit 1
